mysql:
  host: "127.0.0.1"
  port: 3306
  database: "mc"
  username: "root"
  password: "123456"
  ## Don't change this unless the console is spamming errors about SSL.
  ssl: true

# 每次改名花费的金额
cost: 200

## Set to '' if you don't want a prefix.
nickname-prefix: ''

## Max length for a nickname
limit:
  enabled: false
  ## Include colour codes in the count.
  include-color: false
  length: 16

messages:
  nickhis:
    insufficient-arguments: "&4Please use the command like this &6/nickhis &e<playerName>"
    no-result: "玩家 %s (uuid: %s) 没有历史改名记录"
    no-permission: "&4You do not have permission 'mysqlnicks.nickhis' to use this command."
  nick:
    no-console: "&4Only players can use this command."
    no-permission: "&4You do not have permission to use this command."
    insufficient-arguments: "&4Please use the command like this &6/nick &e<nickname>"
    exceeds-limit: "&4Your desired nickname exceeds the limit. Please choose a shorter nickname."
    no-color: "&4You are not allowed to use color your nickname."
    no-codes: "&4You are not allowed to use color codes in your nickname."
    no-hex: "&4You are not allowed to use hex colour codes in your nickname."
    no-formatting: "&4You are not allowed to use code formatting in your nickname."
    no-magic: "&4You are not allowed to use magic in your nickname."
    invalid-player: "&4Unable to find a player with that name."
    target-no-money: "&c你没有足够的金币进行改名"
    target-success: "&a恭喜你改名成功"
    target-failed: "&c改名失败，原因：金币不足"
    error: "&4An error occurred while trying to set your nickname."
    set: "&aSuccessfully set your nickname to &e%nickname%"
    unset: "&aSuccessfully remove your nickname."
    staff:
      error: "&4An error occurred while trying to set &e%player%&4's nickname."
      set: "&aSuccessfully set &e%player%&a's nickname to &e%nickname%"
      unset: "&aSuccessfully removed &e%player%&a's nickname."