name: MySQLNicks
version: ${project.version}
main: co.ignitus.mysqlnicks.MySQLNicks
api-version: "1.13"
softdepend: [PlaceholderAPI, Vault]
authors: ["Ignitus Co", "IllTamer"]
description: Share nicknames across servers with mysql
website: https://ignitus.co

commands:
  nick:
    description: Set your nickname
    aliases: []
  nickhis:
    description: Query one's history nicknames
    aliases: []

permissions:
  mysqlnicks.staff:
    description: Allow permission to use staff commands
  mysqlnicks.nick:
    description: Allow players to change their nicknames
  mysqlnicks.nick.color:
    description: Allow players to use color their nicknames.
  mysqlnicks.nick.color.simple:
    description: Allow players to use normal minecraft colour codes in their nicknames.
  mysqlnicks.nick.color.hex:
    description: Allow players to use hex color codes in their nicknames.
  mysqlnicks.nick.format:
    description: Allow player to use color formatting in their nicknames.
  mysqlnicks.nick.magic:
    description: "Allow player to use magic (&k) in their nicknames."
  mysqlnicks.nickhis:
    description: Allow permission to query one's history nicknames
