name: MySQLNicks
version: ${project.version}
main: co.ignitus.mysqlnicks.MySQLNicks
api-version: "1.13"
softdepend: [PlaceholderAPI]
authors: ["Ignitus Co", "IllTamer"]
description: Share nicknames across servers with mysql
website: https://ignitus.co

commands:
  nick:
    description: Set your nickname
    aliases: [onick, remotenick]
  nickhistory:
    description: Query one's history nicknames
    aliases: [ nickhis ]

permissions:
  mysqlnicks.staff:
    description: Allow permission to use staff commands
  mysqlnicks.nick:
    description: Allow players to change their nicknames
  mysqlnicks.nick.color:
    description: Allow players to use color their nicknames.
  mysqlnicks.nick.color.simple:
    description: Allow players to use normal minecraft colour codes in their nicknames.
  mysqlnicks.nick.color.hex:
    description: Allow players to use hex color codes in their nicknames.
  mysqlnicks.nick.format:
    description: Allow player to use color formatting in their nicknames.
  mysqlnicks.nick.magic:
    description: "Allow player to use magic (&k) in their nicknames."
  mysqlnicks.importnicks:
    description: Grant permission to import nicknames from supported plugins.
  mysqlnicks.exportnicks:
    description: Grant permission to export nicknames to supported plugins.
  mysqlnicks.bypass.nocolor:
    description: Shows colors in the nocolor placeholder
  mysqlnicks.bypass.limit:
    description: Grants permission to bypass character limit
